services:
  db:
    env_file: .env
    image: postgres
    ports: 
      - 5432:5432
    networks:
      - store-network
  store:
    env_file: .env
    environment: 
      - NODE_ENV=prod
    build: .
    ports:
        - 443:3000
    networks:
        - store-network
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
  nginx:
    image: nginx
    ports:
      - 80:80
    networks:
      - store-network
    volumes:
      - type: bind # тип подключения файлов docker
        source: ./nginx.conf    # исходный
        target: /etc/nginx/nginx.conf # целевой
        read_only: true
networks:
  store-network:
version: '2'
