services:
  db:
    env_file: .env
    image: postgres
    ports: 
      - 5432:5432
    networks:
      - store-network
  store:
    env_file: .env
    build: .
    ports:
        - 80:3000
    networks:
        - store-network
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
networks:
  store-network:
version: '2'
